### ISSUE TITLE
New Logo for ReadLater

### ISSUE THREAD

**Issue by Yasujizr** [WillBChang/ReadLater#1]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards.

**Comment by WillBChang** [comment]
Hi @Yasujizr,

ReadLater is expecting you to give her a new icon! I don't have an idea for now, so go ahead to implement yours.

Cheers 🍻

**Comment by Yasujizr** [comment]
![readlater](https://user-images.githubusercontent.com/36993664/47678341-95f0c700-dbd2-11e8-97b2-fc26f2112ea8.jpg)

First logo on a bookmark. I think the name of the readlater is the best defining logo.

---

The second logo is a combination of a page and a bookmark.

---

In the third logo, I used three points. This means that there is no continuation in literature. thought it was nice to readlater.

---

I'm having a problem using the program. I installed it but could not activate it.

**Comment by WillBChang** [comment]
Thanks for your great work, they are all good! I prefer the first logo based on my instinct. It gives me more feelings about simplicity, comfort and fashionableness.

I've opened another issue to deal with the usage problem.

**Comment by Yasujizr** [comment]
I am glad you like it. I created a PR for you, you can accept if you approve. I'll give you a google.drive link with the files.

**Comment by WillBChang** [comment]
Sure thing! 😘

**Comment by Yasujizr** [comment]
hi, 

link in ai. format logo files and information available. thank you. I hope you continue to contribute to the open source. you can write to me anytime.

 https://drive.google.com/open?id=1F30QQ_cVYKlL4ZYpwWEyWI0K8TTKhP5z

**Comment by WillBChang** [comment]
Thanks for your contribute. I will definitely continue to contribute. There still are some features and error handlers to do. You can watch this repo and get update from the later versions.

Keep in touch. ;)
