### ISSUE TITLE
Can't activate the extension

### ISSUE THREAD

**Issue by WillBChang** [WillBChang/ReadLater#2]
>I'm having a problem using the program. I installed it but could not activate it.

_Originally posted by @Yasujizr in https://github.com/WillBChang/ReadLater/issues/1#issuecomment-434069326_

**Comment by WillBChang** [comment]
I guess we have different time zone. Currently I'm developing the v1.2 and it should be released when you wake up. Try it and see if there still has any errors.

If I haven't released it, you can try the steps below.

---
1. Did you download the newest release?
2. Do you have any conflict with the command `Alt+Shift+S` on your Operating System?
3. Try to download this repo and remove the `_config.yml`
	1. Go to `chrome://extensions`
	1.5. If you see an `Error` on the previous installation, please click it and upload a screenshot below.
	2. Click load unpacked and select the downloaded repo.
4. Could you upload a screenshot or screen record about the problem you have occurred?

**Comment by WillBChang** [comment]
Hey @Yasujizr, have a try with the newest [![Read-Later.crx](https://img.shields.io/github/release/willbchang/readlater.svg)](https://github.com/WillBChang/readlater/releases/latest).

Please let me know if there is any question. 😃

**Comment by Yasujizr** [comment]
Hi,

I can't click here. I can not activate. I think chrome is blocking it because it's not in the store. google security is still closed though. I didn't understand either. I'll try and rewrite it on another computer. :)

**Comment by WillBChang** [comment]
1. Download and unzip [Read-Later.zip](https://github.com/WillBChang/ReadLater/releases/download/V1.2.0/Read-Later.zip)
2. Click load unpacked extension and select the folder.

**Comment by Yasujizr** [comment]
ReadLater activated. But now even if I press alt+shift+s does not work. I can't see the plugin when I right click.

![readss](https://user-images.githubusercontent.com/36993664/47809025-e2faa780-dd50-11e8-878c-65ef109c91e0.jpg)

**Comment by Yasujizr** [comment]
Wow! 

It works very well. My stupidity. No update is required. :) Thanks for extension.
